/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Fernanda.Aldaco.de.Luna (https://sketchfab.com/Fernanda.Aldaco.de.Luna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pc-cat-654cea4331b1498cb28003774fb27b3d
Title: PC_Cat
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/pc_cat.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[25.358, 170.851, -23.541]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Orejas_CajaPC_0.geometry}
            material={materials.CajaPC}
            scale={[1.195, 1, 1.171]}
          />
        </group>
        <group
          position={[1.261, 90.016, 12.086]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_Pantalla_CajaPC_0.geometry}
            material={materials.CajaPC}
            scale={[1.225, 1.717, 2.568]}
          />
        </group>
        <group
          position={[1.121, 46.95, -4.739]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Escritorio_Material_#36_0"].geometry}
            material={materials.Material_36}
            scale={[0.706, 1, 1]}
          />
        </group>
        <group position={[1.324, 0, 90.98]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_CajaPC_0.geometry}
            material={materials.CajaPC}
            rotation={[0, 0, -0.175]}
          />
        </group>
        <group position={[0.968, 48.382, 93]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Canasta_Canasta_0.geometry}
            material={materials.Canasta}
            rotation={[0, 0, -0.175]}
            scale={[1.039, 0.942, 1.039]}
          />
        </group>
        <group
          position={[0.988, 58.422, 92.886]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Almohada_Tela_0.geometry}
            material={materials.Tela}
            rotation={[0, 0, -0.175]}
            scale={[1.079, 1, 0.224]}
          />
        </group>
        <group
          position={[-55.71, 142.311, 21.103]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_miniPC2_Metal_0.geometry}
            material={materials.Metal}
            rotation={[0, -0.175, 0]}
          />
        </group>
        <group
          position={[-39.108, 151.684, 18.148]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_miniPC__0.geometry}
            material={materials.Base_miniPC__0}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <group
          position={[-52.856, 132.341, 15.46]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.MiniPC_Metal_0.geometry}
            material={materials.Metal}
            rotation={[Math.PI / 2, 0.175, 0.175]}
            scale={[1, 1, 1.288]}
          />
        </group>
        <group
          position={[-64.215, 135.037, 22.045]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cable_miniPC_General_0.geometry}
            material={materials.General}
            rotation={[1.484, 0, 0]}
          />
        </group>
        <group
          position={[47.218, 71.347, 28.771]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lata1_General_0.geometry}
            material={materials.General}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <group
          position={[54.122, 71.347, 10.892]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lata2_General_0.geometry}
            material={materials.General}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <group
          position={[54.898, 77.23, 9.905]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lata3_General_0.geometry}
            material={materials.General}
            rotation={[0.037, -0.087, 0.015]}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <group
          position={[53.898, 88.378, 8.965]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lata4_General_0.geometry}
            material={materials.General}
            rotation={[0.082, -0.085, 0.012]}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <group
          position={[54.988, 67.015, 2.367]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cable_mouse_General_0.geometry}
            material={materials.General}
            rotation={[Math.PI / 2, -0.087, 0]}
          />
        </group>
        <group
          position={[32.943, 74.792, 0.519]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_cable_mouse__0.geometry}
            material={materials.Base_miniPC__0}
            rotation={[0, 1.33, Math.PI / 2]}
          />
        </group>
        <group
          position={[62.553, 47.71, 2.134]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mouse_General_0.geometry}
            material={materials.General}
            rotation={[1.336, 0.406, 0.09]}
          />
        </group>
        <group
          position={[64.394, 52.049, 6.182]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Scroll_General_0.geometry}
            material={materials.General}
            rotation={[1.279, 0.401, 0.112]}
            scale={[1.029, 2.351, 0.646]}
          />
        </group>
        <group
          position={[47.188, 20.273, 12.94]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cable1_General_0.geometry}
            material={materials.General}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <group
          position={[-14.252, 77.731, -35.503]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_cable1__0.geometry}
            material={materials.Base_miniPC__0}
            rotation={[-1.295, 0, Math.PI]}
            scale={[1.826, 1, 1]}
          />
        </group>
        <group
          position={[-55.462, 34.88, 4.33]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cable2_General_0.geometry}
            material={materials.General}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.29}
          />
        </group>
        <group
          position={[-45.35, 35.97, 18.151]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tubo_General_0.geometry}
            material={materials.General}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <group
          position={[44.803, 7.336, 40.52]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_cableCPU_General_0.geometry}
            material={materials.General}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={0.873}
          />
        </group>
        <group
          position={[-44.914, 70.897, 27.726]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plato_General_0.geometry}
            material={materials.General}
            scale={1.375}
          />
        </group>
        <group
          position={[10.29, 106.721, 32.487]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sticker_General_0.geometry}
            material={materials.General}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <group
          position={[-57.43, 34.88, -7.744]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cable3_General_0.geometry}
            material={materials.General}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.29}
          />
        </group>
        <group
          position={[-6.566, 7.92, 49.062]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_cableCPU2_General_0.geometry}
            material={materials.General}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.873}
          />
        </group>
        <group
          position={[-6.566, 7.062, 37.229]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_cableCPU3_General_0.geometry}
            material={materials.General}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.873}
          />
        </group>
        <group
          position={[59.307, 0.699, 97.404]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.09}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder018_General_0.geometry}
            material={materials.General}
            position={[-4.043, 3.566, 0]}
            rotation={[-Math.PI / 2, -1.134, -Math.PI / 2]}
            scale={[0.306, 0.993, 0.618]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box019_General_0.geometry}
            material={materials.General}
            position={[-8.852, 4.125, -2.208]}
            rotation={[0, 0, -0.087]}
          />
        </group>
        <group position={[1.324, 0, 90.98]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Linea_azul_BASE_0.geometry}
            material={materials.BASE}
            rotation={[0, 0, -0.175]}
          />
        </group>
        <group
          position={[-46.764, 86.731, 25.496]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pez_General_0.geometry}
            material={materials.General}
            rotation={[0.848, 0.601, 0.52]}
            scale={[1.151, 1.791, 0.545]}
          />
        </group>
        <group
          position={[-49.79, 94.52, 17.985]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cola1_General_0.geometry}
            material={materials.General}
            rotation={[0.818, 0.56, -0.315]}
            scale={1.325}
          />
        </group>
        <group
          position={[-54.241, 93.987, 22.308]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cola2_General_0.geometry}
            material={materials.General}
            rotation={[0.818, 0.56, 0.584]}
            scale={1.325}
          />
        </group>
        <group
          position={[-52.856, 132.341, 15.46]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Pantalla_chica_Material_#39_0"].geometry}
            material={materials.Material_39}
            rotation={[Math.PI / 2, 0.175, 0.175]}
            scale={[1, 1, 1.288]}
          />
        </group>
        <group
          position={[2.139, 0.897, 79.165]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <group position={[57.51, 15.365, -0.567]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Papas_General_0.geometry}
              material={materials.General}
              position={[0.693, -0.112, -0.084]}
              scale={0.507}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Papas_General_0_1.geometry}
              material={materials.General}
              position={[-5.771, -5.651, -0.139]}
              rotation={[0, 0, -Math.PI / 3]}
              scale={0.777}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Papas_General_0_2.geometry}
              material={materials.General}
              position={[-4.137, -11.519, -0.139]}
              rotation={[0, 0, 0.262]}
              scale={1.363}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Papas_General_0_3.geometry}
            material={materials.General}
            position={[-60.171, -25.911, -0.224]}
            scale={0.411}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Papas_General_0_4.geometry}
            material={materials.General}
            position={[-53.877, -24.163, -0.195]}
            scale={1.115}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Papas_General_0_5.geometry}
            material={materials.General}
            position={[-51.172, -19.713, -0.979]}
            scale={1.251}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Papas_General_0_6.geometry}
            material={materials.General}
            position={[-56.678, -21.449, 0.011]}
            rotation={[0.087, 0, 0]}
            scale={1.373}
          />
        </group>
        <group
          position={[53.898, 88.378, 8.965]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boquilla_lata1_General_0.geometry}
            material={materials.General}
            rotation={[0.082, -0.085, 0.012]}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <group
          position={[53.357, 82.659, 10.183]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lata5_General_0.geometry}
            material={materials.General}
            rotation={[0, 0.007, 0]}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <group
          position={[53.357, 82.659, 10.183]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boquilla_lata2_General_0.geometry}
            material={materials.General}
            rotation={[0, 0.007, 0]}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <group
          position={[54.898, 77.23, 9.905]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boquilla_lata3_General_0.geometry}
            material={materials.General}
            rotation={[0.037, -0.087, 0.015]}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <group
          position={[54.122, 71.347, 10.892]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boquilla_lata4_General_0.geometry}
            material={materials.General}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <group
          position={[47.218, 71.347, 28.771]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boquilla_lata5_General_0.geometry}
            material={materials.General}
            scale={[1.232, 1.232, 1.052]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Caja_PC_CajaPC_0.geometry}
          material={materials.CajaPC}
          position={[1.121, 100.152, -6.458]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Caja_CajaPC_0.geometry}
          material={materials.CajaPC}
          position={[1.121, 71.096, -6.458]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Paneles_Material_#39_0"].geometry}
          material={materials.Material_39}
          position={[1.121, 71.096, -6.458]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Panel_huella_Material_#39_0"].geometry}
          material={materials.Material_39}
          position={[1.121, 71.096, -6.458]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_cilindro_BASE_0.geometry}
          material={materials.BASE}
          position={[1.121, 0.339, -4.739]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CPU_CPU_0.geometry}
          material={materials.material}
          position={[19.08, 0.345, 37.135]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pantalla_Pantalla_0.geometry}
          material={materials.Pantalla}
          position={[1.121, 100.152, -6.458]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_escritorio_BASE_0.geometry}
          material={materials.BASE}
          position={[1.121, 0.339, -4.739]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pc_cat.glb");
